platform :ios, '13.0'

install! 'cocoapods',
         :deterministic_uuids => false

target 'OCAppBoxExample' do
  project 'OCAppBoxExample.xcodeproj'
  use_frameworks! :linkage => :static

  pod 'OCAppBox', :path => '..'

  target 'OCAppBoxExampleTests' do
    inherit! :search_paths
  end
end
