#import "__PAGE_CLASS_NAME__.h"

#import <OCAppBox.h>

@interface __PAGE_CLASS_NAME__ ()

@property (nonatomic, weak) OCBAppContext *appContext;
@property (nonatomic, strong) UIStackView *stackView;
@property (nonatomic, strong) UILabel *titleLabel;
@property (nonatomic, strong) UILabel *detailLabel;
@property (nonatomic, strong) UIButton *primaryButton;
@property (nonatomic, strong) UIButton *secondaryButton;
@property (nonatomic, assign) BOOL presentingEmptyState;

@end

@implementation __PAGE_CLASS_NAME__

- (instancetype)initWithAppContext:(OCBAppContext *)appContext
{
    self = [super initWithNibName:nil bundle:nil];
    if (self) {
        _appContext = appContext;
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];

    self.title = @"__DISPLAY_TITLE__";
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways;

    self.stackView = [[UIStackView alloc] initWithFrame:CGRectZero];
    self.stackView.translatesAutoresizingMaskIntoConstraints = NO;
    self.stackView.axis = UILayoutConstraintAxisVertical;
    self.stackView.spacing = 16.0;

    self.titleLabel = [[UILabel alloc] initWithFrame:CGRectZero];
    self.titleLabel.text = @"__DISPLAY_TITLE__";
    self.titleLabel.font = [UIFont systemFontOfSize:30.0 weight:UIFontWeightBold];
    self.titleLabel.textColor = [OCBThemeManager sharedManager].primaryTextColor;
    self.titleLabel.numberOfLines = 0;

    self.detailLabel = [[UILabel alloc] initWithFrame:CGRectZero];
    self.detailLabel.text = @"Generated by Scripts/generate_page.rb. This plain page is ready for form fields, detail cards or simple business actions.";
    self.detailLabel.font = [UIFont systemFontOfSize:16.0];
    self.detailLabel.textColor = [OCBThemeManager sharedManager].secondaryTextColor;
    self.detailLabel.numberOfLines = 0;

    self.primaryButton = [self actionButtonWithTitle:@"Show Toast" action:@selector(showDemoToast)];
    self.secondaryButton = [self actionButtonWithTitle:@"Toggle Empty State" action:@selector(toggleEmptyState)];

    [self.contentView addSubview:self.stackView];
    [self.stackView addArrangedSubview:self.titleLabel];
    [self.stackView addArrangedSubview:self.detailLabel];
    [self.stackView addArrangedSubview:self.primaryButton];
    [self.stackView addArrangedSubview:self.secondaryButton];

    [NSLayoutConstraint activateConstraints:@[
        [self.stackView.topAnchor constraintEqualToAnchor:self.contentView.topAnchor constant:32.0],
        [self.stackView.leadingAnchor constraintEqualToAnchor:self.contentView.leadingAnchor constant:24.0],
        [self.stackView.trailingAnchor constraintEqualToAnchor:self.contentView.trailingAnchor constant:-24.0]
    ]];
}

- (UIButton *)actionButtonWithTitle:(NSString *)title action:(SEL)action
{
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    button.titleLabel.font = [UIFont systemFontOfSize:16.0 weight:UIFontWeightSemibold];
    button.backgroundColor = [OCBThemeManager sharedManager].tintColor;
    [button setTitle:title forState:UIControlStateNormal];
    [button setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    button.layer.cornerRadius = 12.0;
    [button.heightAnchor constraintEqualToConstant:52.0].active = YES;
    [button addTarget:self action:action forControlEvents:UIControlEventTouchUpInside];
    return button;
}

- (void)showDemoToast
{
    [self showToastWithText:@"__DISPLAY_TITLE__ page is ready."];
}

- (void)toggleEmptyState
{
    self.presentingEmptyState = !self.presentingEmptyState;
    if (self.presentingEmptyState) {
        __weak typeof(self) weakSelf = self;
        [self showEmptyWithTitle:@"No Content Yet"
                          detail:@"Use this hook for empty list state, failed search result, or onboarding hints."
                     actionTitle:@"Reload"
                   actionHandler:^{
            __strong typeof(weakSelf) strongSelf = weakSelf;
            [strongSelf hideEmpty];
            strongSelf.presentingEmptyState = NO;
            [strongSelf showToastWithText:@"Reload action tapped."];
        }];
    } else {
        [self hideEmpty];
    }
}

@end
