#import "OCBProfileViewController.h"

#import <UI/Theme/OCBThemeManager.h>
#import "UIView+OCBAdditions.h"

@interface OCBProfileViewController ()

@property (nonatomic, weak) OCBAppContext *appContext;
@property (nonatomic, strong) UILabel *titleLabel;
@property (nonatomic, strong) UILabel *detailLabel;
@property (nonatomic, strong) UIButton *actionButton;
@property (nonatomic, assign) BOOL presentingEmptyState;

@end

@implementation OCBProfileViewController

- (instancetype)initWithAppContext:(OCBAppContext *)appContext
{
    self = [super initWithNibName:nil bundle:nil];
    if (self) {
        _appContext = appContext;
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];

    self.title = @"Profile";
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways;

    self.titleLabel = [[UILabel alloc] initWithFrame:CGRectZero];
    self.titleLabel.text = @"Profile";
    self.titleLabel.font = [UIFont boldSystemFontOfSize:30.0];
    self.titleLabel.textAlignment = NSTextAlignmentCenter;
    self.titleLabel.textColor = [OCBThemeManager sharedManager].primaryTextColor;

    self.detailLabel = [[UILabel alloc] initWithFrame:CGRectZero];
    self.detailLabel.numberOfLines = 0;
    self.detailLabel.textAlignment = NSTextAlignmentCenter;
    self.detailLabel.font = [UIFont systemFontOfSize:16.0];
    self.detailLabel.textColor = [OCBThemeManager sharedManager].secondaryTextColor;
    self.detailLabel.text = @"Generated by Scripts/generate_module.rb.\nRegister this module and route to start building business pages.";

    self.actionButton = [UIButton buttonWithType:UIButtonTypeSystem];
    self.actionButton.titleLabel.font = [UIFont systemFontOfSize:16.0 weight:UIFontWeightSemibold];
    self.actionButton.backgroundColor = [OCBThemeManager sharedManager].tintColor;
    [self.actionButton setTitle:@"Toggle Empty State" forState:UIControlStateNormal];
    [self.actionButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    self.actionButton.layer.cornerRadius = 12.0;
    [self.actionButton addTarget:self action:@selector(toggleEmptyState) forControlEvents:UIControlEventTouchUpInside];

    [self.contentView addSubview:self.titleLabel];
    [self.contentView addSubview:self.detailLabel];
    [self.contentView addSubview:self.actionButton];
}

- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];

    CGFloat width = self.contentView.ocb_width;
    CGFloat top = 56.0;
    self.titleLabel.frame = CGRectMake(24.0, top, width - 48.0, 36.0);
    self.detailLabel.frame = CGRectMake(24.0, CGRectGetMaxY(self.titleLabel.frame) + 18.0, width - 48.0, 76.0);
    self.actionButton.frame = CGRectMake(32.0, CGRectGetMaxY(self.detailLabel.frame) + 28.0, width - 64.0, 52.0);
}

- (void)toggleEmptyState
{
    self.presentingEmptyState = !self.presentingEmptyState;
    if (self.presentingEmptyState) {
        [self showEmptyWithTitle:@"Profile"
                          detail:@"This is the default empty-state hook for the generated module."];
    } else {
        [self hideEmpty];
    }
}

@end
